create table application
(
    application_id bigint primary key generated by default as identity,
    client_id      bigint references client (client_id) on delete cascade not null,
    credit_id      bigint references credit (credit_id) on delete cascade not null,
    status         varchar                                                not null,
    creation_date  timestamp                                              not null,
    applied_offer  jsonb                                                  not null,
    sign_date      timestamp                                              not null,
    ses_code       int,
    status_history jsonb                                                  not null
)