create table Client
(
    client_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name       varchar(30),
    last_name        varchar(30),
    middle_name      varchar(30),
    birth_date       DATE,
    email            varchar unique,
    gender           varchar,
    marital_status   varchar,
    dependent_amount int,
    passport_id      jsonb,
    employment_id    jsonb,
    account          varchar
)